import type { FormulaInput, FormulaType } from "../../schemas/formula";

export interface FormulaExample extends FormulaInput {
  title: string;
  summary: string;
}

export const examples: FormulaExample[] = [
  {
    id: "weighted-loss",
    title: "Weighted Multi-Objective Loss",
    summary: "Blend reconstruction, adversarial, and perceptual goals into one training target.",
    latex: "L = \\lambda_1 L_{rec} + \\lambda_2 L_{adv} + \\lambda_3 L_{perceptual}",
    context: "A common loss function in image generation papers.",
    domain: "ai_ml",
    selectedType: "weighted_loss",
  },
  {
    id: "softmax",
    title: "Softmax with Temperature",
    summary: "Convert logits into competing probabilities and explore temperature effects.",
    latex: "p_i = \\frac{e^{z_i / T}}{\\sum_j e^{z_j / T}}",
    context: "Used to convert logits into probabilities.",
    domain: "ai_ml",
    selectedType: "softmax",
  },
  {
    id: "sigmoid",
    title: "Sigmoid Mapping",
    summary: "Map any real-valued score into a smooth 0 to 1 value.",
    latex: "\\sigma(x) = \\frac{1}{1 + e^{-x}}",
    context: "Used as a binary probability or gate.",
    domain: "math_stats",
    selectedType: "sigmoid",
  },
  {
    id: "gradient-descent",
    title: "Gradient Descent Update Rule",
    summary: "Step opposite the loss gradient and inspect learning-rate behavior.",
    latex: "\\theta_{t+1} = \\theta_t - \\eta \\nabla_\\theta L(\\theta_t)",
    context: "Basic optimization update used in machine learning.",
    domain: "ai_ml",
    selectedType: "gradient_descent",
  },
  {
    id: "attention",
    title: "Scaled Dot-Product Attention",
    summary: "Read Transformer attention as query-key scoring, softmax weighting, and value mixing.",
    latex: "\\mathrm{Attention}(Q,K,V)=\\mathrm{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V",
    context: "The core attention operation inside Transformer blocks.",
    domain: "ai_ml",
    selectedType: "scaled_dot_product_attention",
  },
  {
    id: "layer-norm",
    title: "Layer Normalization",
    summary: "Normalize one activation vector with local mean and variance, then apply learned scale and shift.",
    latex: "\\mathrm{LN}(x)=\\gamma\\frac{x-\\mu}{\\sqrt{\\sigma^2+\\epsilon}}+\\beta",
    context: "Normalization formula used throughout Transformer and deep-learning architectures.",
    domain: "ai_ml",
    selectedType: "layer_norm",
  },
  {
    id: "adam",
    title: "Adam Optimizer Update",
    summary: "Use bias-corrected gradient moments to form an adaptive parameter update.",
    latex: "\\theta_t=\\theta_{t-1}-\\eta\\frac{\\hat m_t}{\\sqrt{\\hat v_t}+\\epsilon}",
    context: "Adam optimizer update for neural network training.",
    domain: "ai_ml",
    selectedType: "adam_optimizer",
  },
  {
    id: "cross-entropy",
    title: "Cross Entropy Loss",
    summary: "Penalize predicted probabilities that disagree with the true label.",
    latex: "L = -\\sum_i y_i \\log p_i",
    context: "Classification loss paired with softmax probabilities.",
    domain: "ai_ml",
    selectedType: "cross_entropy",
  },
  {
    id: "bayes-rule",
    title: "Bayes' Rule",
    summary: "Update a prior belief after observing evidence.",
    latex: "P(A \\mid B) = \\frac{P(B \\mid A)P(A)}{P(B)}",
    context: "A probability identity for posterior inference.",
    domain: "math_stats",
    selectedType: "bayes_rule",
  },
  {
    id: "combination",
    title: "Combination Count",
    summary: "Count unordered ways to choose k items from n.",
    latex: "\\binom{n}{k} = \\frac{n!}{k!(n-k)!}",
    context: "A basic formula in combinatorics and discrete math.",
    domain: "discrete_math",
    selectedType: "combination",
  },
  {
    id: "pigeonhole",
    title: "Pigeonhole Principle",
    summary: "Guarantee that some box receives at least the ceiling-average number of objects.",
    latex: "\\max_i |B_i| \\ge \\left\\lceil \\frac{n}{m} \\right\\rceil",
    context: "A counting guarantee in discrete math.",
    domain: "discrete_math",
    selectedType: "pigeonhole_principle",
  },
  {
    id: "de-morgan",
    title: "De Morgan's Law",
    summary: "Negating a union becomes an intersection of complements.",
    latex: "\\overline{A\\cup B}=\\bar A\\cap\\bar B",
    context: "Set identity and Boolean logic rewrite.",
    domain: "discrete_math",
    selectedType: "de_morgan_law",
  },
  {
    id: "modular-congruence",
    title: "Modular Congruence",
    summary: "Compare integers by whether they share the same remainder under a modulus.",
    latex: "a\\equiv b\\pmod n \\iff n\\mid(a-b)",
    context: "A modular arithmetic relation from number theory.",
    domain: "discrete_math",
    selectedType: "modular_congruence",
  },
  {
    id: "logic-quantifier",
    title: "Quantified Relation",
    summary: "Read a first-order logic statement with nested quantifiers.",
    latex: "\\forall x\\in A,\\exists y\\in B: R(x,y)",
    context: "A predicate logic formula in discrete mathematics.",
    domain: "discrete_math",
    selectedType: "logic_quantifier",
  },
  {
    id: "set-union",
    title: "Inclusion-Exclusion for Two Sets",
    summary: "Count a union without double-counting the overlap.",
    latex: "|A \\cup B| = |A| + |B| - |A \\cap B|",
    context: "A set identity from discrete mathematics.",
    domain: "discrete_math",
    selectedType: "set_identity",
  },
  {
    id: "graph-degree",
    title: "Graph Degree Sum",
    summary: "Every undirected edge contributes two degree counts.",
    latex: "\\sum_{v \\in V} \\deg(v) = 2|E|",
    context: "The handshaking lemma in graph theory.",
    domain: "discrete_math",
    selectedType: "graph_degree",
  },
];

export const formulaTypeLabels: Record<FormulaType | "auto", string> = {
  auto: "Auto Detect",
  weighted_loss: "Weighted Loss",
  softmax: "Softmax",
  sigmoid: "Sigmoid",
  gradient_descent: "Gradient Descent",
  scaled_dot_product_attention: "Scaled Dot-Product Attention",
  layer_norm: "LayerNorm",
  adam_optimizer: "Adam Optimizer",
  cross_entropy: "Cross Entropy",
  bayes_rule: "Bayes' Rule",
  combination: "Combination",
  permutation: "Permutation",
  set_identity: "Set Identity",
  graph_degree: "Graph Degree",
  logic_quantifier: "Logic / Quantifier",
  recurrence_relation: "Recurrence Relation",
  pigeonhole_principle: "Pigeonhole Principle",
  de_morgan_law: "De Morgan's Law",
  modular_congruence: "Modular Congruence",
  unknown: "Unknown",
};

export function getExample(id: string | null): FormulaExample | undefined {
  return examples.find((example) => example.id === id);
}
